[profile.default]
src = 'src'
out = "out"
libs = ['node_modules', 'lib']
test = 'test'
ffi = true
ast = false
build_info = false
# extra_output = ["storageLayout"]
cache_path = 'cache_forge'
solc-version = '0.8.24'
optimizer = true
optimizer_runs = 200
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "hardhat/=node_modules/hardhat/",
]
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/d6c48bdea36f4e88a8a907c882ba21fc"
[fmt]
single_line_statement_blocks = "multi"
sort_imports = true
multiline_func_header = "params_first"
contract_new_lines = true
override_spacing = true
