name: CRON Jobs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
env:
  AIRSTACK_API_URL: ${{ secrets.AIRSTACK_API_URL }}
  AIRSTACK_API_KEY: ${{ secrets.AIRSTACK_API_KEY }}
  HUB_URL: ${{ secrets.HUB_URL }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}
  GRAPH_ENDPOINT: ${{ secrets.GRAPH_ENDPOINT }}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Start pnpm cron
        run: pnpm cron