name: Sync fork for Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_run' && 'main' || github.head_ref || github.ref_name }}
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.FORK_KEY }}
      - name: Push to fork repo
        env:
          USE_SSH: true
        run: |
          git remote add fork git@github.com:lutralabs-bot/ees.git
          git config --global user.email "info@lutralabs.io"
          git config --global user.name "lutralabs-bot"
          git push fork --force
